[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/milespossing/nvim-lazy.git"
    refreshPeriod = "168h"

[".nu_scripts"]
    type = "git-repo"
    url = "https://github.com/milespossing/nu_scripts.git"
    refreshPeriod = "168h"
