[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
# macos
option_as_alt = "both"

# [shell]
# program = "/Users/miles/.cargo/bin/zellij"
# args = [
#      "options",
#      "--default-shell",
#      "/Users/miles/.cargo/bin/nu"
# ]
